### ISSUE TITLE
In array raise Not Implemented error

### ISSUE THREAD

**Issue by kmmndr** [lloeki/rebel#2]
It would be nice to allow arrays as argument for sql `in`
```ruby
Rebel::SQL.name('foo').in([1, 2])
NotImplementedError: [1, 2]
from /home/thomas/.local/lib/ry/rubies/2.3.3/lib/ruby/gems/2.3.0/gems/rebel-0.3.3/lib/rebel/sql.rb:287:in `value'
```

**Comment by lloeki** [comment]
This is [by design](https://github.com/lloeki/rebel/blob/96d2f9991a96cdd4ae85765bf2c7f71fb82b627a/test/test_raw.rb#L67), use splats.
