### ISSUE TITLE
Select without from

### ISSUE THREAD

**Issue by kmmndr** [lloeki/rebel#3]
From argument seems to be mandatory for Rebel::SQL.  
Is it possible to allow `SELECT` without `FROM` ?
```ruby
Rebel::SQL.select(Rebel::SQL.raw('NOW()'))
=> "      SELECT NOW() FROM \n      \n      \n      \n      \n"
```

**Comment by lloeki** [comment]
Implemented in a3712ceefd603ac12c1e4a6bb79e3f4cb37276e4
